name: Housekeeping

on:
  pull_request:
    types: [closed]
  push:
    branches: [main, develop]

concurrency:
  group: housekeeping-${{ github.ref }}
  cancel-in-progress: true

jobs:
  housekeeping:
    name: Housekeeping
    uses: banua-coder/banua-coder-workflow/.github/workflows/housekeeping.yml@main
    with:
      protected-branches: 'main,develop'
